# Demonstration.lsf:
# make Make a flexible filter
# with bandwidth recovery

make2stageFilter;
cdc = cdc3; importCDC;
setposition(cdc3,200,130);
cdc = cdc4; importCDC;
setposition(cdc4,200,220);

disconnect(cdc1,"opt3",ONA,"input 2");
connect(cdc1,"opt3",cdc3,"opt1");
connect(cdc3,"opt2",cdc4,"opt1");
connect(cdc3,"opt4",cdc4,"opt3");
connect(cdc3,"opt3",ONA,"input 3");
connect(cdc4,"opt2",ONA,"input 2");
quickRun;